apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
spec:
  releaseName: postgresql
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "11.2.1"
  interval: 01h
  install:
    remediation:
      retries: 3
  # https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml
  values:
