apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nodejs
spec:
  releaseName: node
  chart:
    spec:
      chart: node
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "18.0.0"
  interval: 01h
  install:
    remediation:
      retries: 3
  # https://github.com/bitnami/charts/blob/master/bitnami/node/values.yaml
  values:
