apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: polaris
spec:
  releaseName: polaris
  chart:
    spec:
      chart: polaris
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable
        namespace: flux-system
      version: "5.1.0"
  interval: 01h
  install:
    remediation:
      retries: 3
  # https://github.com/FairwindsOps/charts/blob/master/stable/polaris/values.yaml
  values:
